package org.com.entities;

// Generated 30 janv. 2016 11:57:34 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "retrait")
public class Transaction implements java.io.Serializable {

	private Integer idTransaction;
	private Compte compte;
	private Utilisateur utilisateur;
	private String dateTransaction;
	private double montant;
	private String valide;

	public Transaction() {
	}

	public Transaction(Compte compte, Utilisateur utilisateur,
			String dateTransaction, double montant, String valide) {
		this.compte = compte;
		this.utilisateur = utilisateur;
		this.dateTransaction = dateTransaction;
		this.montant = montant;
		this.valide = valide;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTransaction", unique = true, nullable = false)
	public Integer getIdTransaction() {
		return this.idTransaction;
	}

	public void setIdTransaction(Integer idTransaction) {
		this.idTransaction = idTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codeCompte", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "dateTransaction", nullable = false, length = 180)
	public String getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(String dateTransaction) {
		this.dateTransaction = dateTransaction;
	}

	@Column(name = "montant", nullable = false, precision = 22, scale = 0)
	public double getMontant() {
		return this.montant;
	}

	public void setMontant(double montant) {
		this.montant = montant;
	}

	@Column(name = "valide", nullable = false, length = 100)
	public String getValide() {
		return this.valide;
	}

	public void setValide(String valide) {
		this.valide = valide;
	}

}
